private _return = [];

//These arrays are purely for organisation, it doesn't actually matter what you put in which, you could put everything in 1 array if you want
private _helmetArray = [];

private _goggleBlacklist = [
	"G_Diving",
	"G_I_Diving",
	"G_O_Diving",
	"G_B_Diving",
	"G_AirPurifyingRespirator_02_black_F",
	"G_AirPurifyingRespirator_02_olive_F",
	"G_AirPurifyingRespirator_02_sand_F",
	"G_AirPurifyingRespirator_01_F",
	"G_Blindfold_01_black_F",
	"G_Blindfold_01_white_F",
	"G_RegulatorMask_F",
	"G_Respirator_blue_F",
	"G_Respirator_white_F",
	"G_Respirator_yellow_F",
	"SP_GasMask_Black",
    "SP_Balaclava_Hamas",
    "SP_Balaclava_HamasBlack",
	"CUP_PMC_G_thug",
    "G_Armband_blk_F",
    "G_Armband_pnk_F",
    "G_Armband_teal_F",
    "G_Armband_blu_F",
    "G_Armband_dblu_F",
    "G_Armband_grn_F",
    "G_Armband_ligblu_F",
    "G_Armband_navblu_F",
    "G_Armband_org_F",
    "G_Armband_pur_F",
    "G_Armband_red_F",
    "G_Armband_darred_F",
    "G_Armband_wht_F",
    "G_Armband_yel_F",
    "G_Armband_IDAP_F",
    "G_Armband_Cross_F",
    "G_Armband_Crescent_F",
    "G_Armband_Diamond_F",
    "G_Armband_UN_F",
    "G_Armband_ION_F",
    "G_Armband_MP_F",
    "G_Armband_MP2_F",
    "G_Armband_press_F",
    "G_Armband_ard_F",
    "G_Armband_bic_F",
    "G_Armband_gpr_F",
    "G_Armband_gro_F",
    "G_Armband_kar_F",
    "G_Armband_nlom_F",
    "G_Armband_slom_F",
    "G_Armband_hivis_F",
    "G_Armband_hivis2_F",
    "G_Armband_NATO_F",
    "G_Armband_lensemble_F",
    "G_Armband_napa_F",
    "G_Armband_cdf_F",
    "G_Armband_afia_F",
    "G_Armband_fia2_F",
    "G_Armband_cpol_F",
    "G_Armband_gendarmerie_F",
    "G_Armband_gendarmerie2_F",
    "G_Armband_horizon_F",
    "G_Armband_racs_F",
    "G_Armband_sla_F",
    "G_Armband_sehrenist_F",
    "G_Armband_ldf_F",
    "G_Armband_aaf_F",
    "G_Armband_sfia_F",
    "G_Armband_tura_F",
    "G_Armband_tak_F",
    "G_Armband_tak2_F",
    "G_Armband_tak3_F",
    "G_Armband_chdkz_F",
    "G_Armband_FIA_F",
    "G_Armband_csat_F",
    "G_Armband_vip_F",
    "G_Armband_blk_alt_F",
    "G_Armband_blu_alt_F",
    "G_Armband_dblu_alt_F",
    "G_Armband_grn_alt_F",
    "G_Armband_ligblu_alt_F",
    "G_Armband_navblu_alt_F",
    "G_Armband_org_alt_F",
    "G_Armband_pur_alt_F",
    "G_Armband_red_alt_F",
    "G_Armband_darred_alt_F",
    "G_Armband_teal_alt_F",
    "G_Armband_wht_alt_F",
    "G_Armband_pnk_alt_F",
    "G_Armband_yel_alt_F",
    "G_Armband_IDAP_alt_F",
    "G_Armband_Cross_alt_F",
    "G_Armband_Crescent_alt_F",
    "G_Armband_Diamond_alt_F",
    "G_Armband_gendarmerie_alt_F",
    "G_Armband_gendarmerie2_alt_F",
    "G_Armband_ard_alt_F",
    "G_Armband_bic_alt_F",
    "G_Armband_gpr_alt_F",
    "G_Armband_gro_alt_F",
    "G_Armband_kar_alt_F",
    "G_Armband_nlom_alt_F",
    "G_Armband_slom_alt_F",
    "G_Armband_racs_alt_F",
    "G_Armband_sla_alt_F",
    "G_Armband_sehrenist_alt_F",
    "G_Armband_ldf_alt_F",
    "G_Armband_aaf_alt_F",
    "G_Armband_sfia_alt_F",
    "G_Armband_cdf_alt_F",
    "G_Armband_afia_alt_F",
    "G_Armband_fia2_alt_F",
    "G_Armband_cpol_alt_F",
    "G_Armband_tura_alt_F",
    "G_Armband_tak_alt_F",
    "G_Armband_tak2_alt_F",
    "G_Armband_tak3_alt_F",
    "G_Armband_UN_alt_F",
    "G_Armband_ION_alt_F",
    "G_Armband_MP_alt_F",
    "G_Armband_MP2_alt_F",
    "G_Armband_press_alt_F",
    "G_Armband_hivis_alt_F",
    "G_Armband_hivis2_alt_F",
    "G_Armband_NATO_alt_F",
    "G_Armband_lensemble_alt_F",
    "G_Armband_horizon_alt_F",
    "G_Armband_napa_alt_F",
    "G_Armband_chdkz_alt_F",
    "G_Armband_csat_alt_F",
    "G_Armband_vip_alt_F",
    "G_Armband_FIA_alt_F",
	"G_Headband_blk_alt_F",
	"G_Headband_blk_F",
	"G_Headband_blu_alt_F",
	"G_Headband_blu_F",
	"G_Headband_dblu_alt_F",
	"G_Headband_dblu_F",
	"G_Headband_darred_alt_F",
	"G_Headband_darred_F",
	"G_Headband_grn_alt_F",
	"G_Headband_grn_F",
	"G_Headband_ligblu_alt_F",
	"G_Headband_ligblu_F",
	"G_Headband_navblu_alt_F",
	"G_Headband_navblu_F",
	"G_Headband_org_alt_F",
	"G_Headband_org_F",
	"G_Headband_pnk_alt_F",
	"G_Headband_pnk_F",
	"G_Headband_pur_alt_F",
	"G_Headband_pur_F",
	"G_Headband_red_alt_F",
	"G_Headband_red_F",
	"G_Headband_teal_alt_F",
	"G_Headband_teal_F",
	"G_Headband_wht_alt_F",
	"G_Headband_wht_F",
	"G_Headband_yel_alt_F",
	"G_Headband_yel_F"
];


//Gets all facewear defined in CfgGoggles
private _configCfgGoggles = configFile >> "CfgGlasses";
private _goggleArray = [];
{
    _goggleArray pushBackUnique (configName _x);
} foreach configProperties [_configCfgGoggles, "isClass _x && {(if (isNumber (_x >> 'scopeArsenal')) then {getNumber (_x >> 'scopeArsenal')} else {getNumber (_x >> 'scope')}) == 2}", true];

_goggleArray = _goggleArray - _goggleBlacklist;

private _uniformArray = [];

private _vestArray = [];

private _backpackArray = [];

private _itemArray = [
	"ACE_fieldDressing",
	"ACE_epinephrine",
	"ACE_morphine",
	"ACE_splint",
	"ACE_tourniquet",
	"ACRE_PRC343",
	"ACE_artilleryTable",
	"ACE_MapTools",
	"acex_intelitems_notepad",
	"ACE_PlottingBoard"
];

private _weaponArray = [];

private _attachmentArray = [];

private _magazineArray = [];

_return = _helmetArray + _goggleArray + _uniformArray + _vestArray + _backpackArray + _itemArray + _weaponArray + _attachmentArray + _magazineArray;
_return = _return arrayIntersect _return;

_return